name: Compile on MacOS (latest) with gnu compilers

on: [ push, pull_request ]

jobs:
  compile-with-amrex_gnu:
    name: Compile thornado on MacOS (latest) with gnu compilers
    runs-on: macos-latest
    env:
      THORNADO_MACHINE: gh-runner_macos-latest_gnu
    steps:
      - name: Checkout thornado
        uses: actions/checkout@v3

      - name: Checkout weaklib
        uses: actions/checkout@v3
        with:
          repository: starkiller-astro/weaklib
          path: weaklib

      - name: Checkout amrex
        uses: actions/checkout@v3
        with:
          repository: dunhamsj/amrex
          path: amrex
          ref: MeshRefinement_DG

      - name: Download and install homebrew and dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo ""
          echo "brew install gcc"
                brew install gcc
          GCC_VERSION=`ls /usr/local/Cellar/gcc`
          echo "/usr/local/Cellar/gcc/${GCC_VERSION}/bin" >> ${GITHUB_PATH}
          echo ""
          echo "brew install gfortran"
                brew install gfortran
          echo ""
          echo "brew install open-mpi"
                brew install open-mpi
          OMPI_VERSION=`ls /usr/local/Cellar/open-mpi`
          echo "/usr/local/Cellar/open-mpi/${OMPI_VERSION}/bin" >> ${GITHUB_PATH}
          echo ""
          echo "brew install hdf5"
                brew install hdf5
          HDF5_VERSION=`ls /usr/local/Cellar/hdf5`
          echo "HDF5_INC=/usr/local/Cellar/hdf5/${HDF5_VERSION}/include" >> ${GITHUB_ENV}
          echo "HDF5_LIB=/usr/local/Cellar/hdf5/${HDF5_VERSION}/lib"     >> ${GITHUB_ENV}
          echo ""
          echo "brew install lapack"
                brew install lapack
          LAPACK_VERSION=`ls /usr/local/Cellar/lapack`
          echo "LAPACK_LIB=/usr/local/Cellar/lapack/${LAPACK_VERSION}/lib" >> ${GITHUB_ENV}
          echo "BLAS_LIB=/usr/local/Cellar/lapack/${LAPACK_VERSION}/lib"   >> ${GITHUB_ENV}

      - name: Set Environment Variables
        run: |
          echo "THORNADO_DIR=${GITHUB_WORKSPACE}"        >> ${GITHUB_ENV}
          echo "WEAKLIB_DIR=${GITHUB_WORKSPACE}/weaklib" >> ${GITHUB_ENV}
          echo "AMREX_DIR=${GITHUB_WORKSPACE}/amrex"     >> ${GITHUB_ENV}

      - name: Find Stuff
        run: |
          echo ""
          echo "which mpicxx"
                which mpicxx
          echo ""
          echo "which mpif90"
                which mpif90
          echo ""
          echo "mpif90 --version"
                mpif90 --version
          echo ""
          echo "find /usr/local/Cellar -iname \"*hdf5.mod\""
                find /usr/local/Cellar -iname  "*hdf5.mod"
          echo ""
          echo "find /usr/local/Cellar -iname \"*libhdf5_fortran*\""
                find /usr/local/Cellar -iname  "*libhdf5_fortran*"
          echo ""
          echo "find /usr/local/Cellar -iname \"*lapack*\""
                find /usr/local/Cellar -iname  "*lapack*"
          echo ""
          echo "find /usr/local/Cellar -iname \"*blas*\""
                find /usr/local/Cellar -iname  "*blas*"
          echo ""
          echo "find /usr/local/Cellar -iname \"*mpi.mod\""
                find /usr/local/Cellar -iname  "*mpi.mod"

      - name: Generate make.out and make.err
        run: |
          cd ${THORNADO_DIR}/SandBox/AMReX/Euler_Relativistic_IDEAL_MR
          make print-INCLUDE_LOCATIONS >  make.out
          make print-LIBRARY_LOCATIONS >> make.out
          make print-VPATH_LOCATIONS   >> make.out
          make print-LIBRARIES         >> make.out
          sh ${THORNADO_DIR}/run.sh >> make.out 2> make.err
          cat make.out
          cat make.err
          make realclean

      - name: Compile SandBox/AMReX/Euler_Relativistic_IDEAL_MR
        run: |
          cd ${THORNADO_DIR}/SandBox/AMReX/Euler_Relativistic_IDEAL_MR
          make
          make realclean
