name: Compile with nvhpc compiler

on:
  push:
    branches: [ InterfaceWithPoseidon ]
  pull_request:
    branches: [ InterfaceWithPoseidon ]

jobs:
  compile-with-nvhpc:
    name: Compile thornado with nvhpc on Ubuntu
    runs-on: ubuntu-latest
    env:
      THORNADO_MACHINE: gh-runner_nvhpc
      THORNADO_DIR: .
      NVHPC_DIR: /opt/nvidia/hpc_sdk/Linux_x86_64/22.7
    steps:
      - uses: actions/checkout@v3
        #      - run: sudo apt-get update -y
        #      - run: sudo apt-get install -y libhdf5-dev liblapack-dev libopenmpi-dev
        #      - run: wget https://developer.download.nvidia.com/hpc-sdk/22.7/nvhpc_2022_227_Linux_x86_64_cuda_11.7.tar.gz
        #      - run: tar xpzf nvhpc_2022_227_Linux_x86_64_cuda_11.7.tar.gz
        #      - run: nvhpc_2022_227_Linux_x86_64_cuda_11.7/install
        #      - run: export PATH=${NVHPC_DIR}/comm_libs/mpi/bin:$PATH
        #      - run: export MANPATH=$MANPATH:${NVHPC_DIR}/comm_libs/mpi/man
        #      - run: cd ${THORNADO_DIR}/SandBox/dgExperiments_Euler_Relativistic_IDEAL/Executables_nvhpc/
      - run: pwd
      - run: ls
      - run: printenv | grep THORNADO
