name: Compile with nvhpc compiler

on:
  push:
    branches: [ InterfaceWithPoseidon ]
  pull_request:
    branches: [ InterfaceWithPoseidon ]

jobs:
  compile-with-nvhpc:
    name: Compile thornado with nvhpc on Ubuntu
    runs-on: ubuntu-20.04
    env:
      THORNADO_MACHINE: gh-runner_nvhpc
      THORNADO_DIR: .
      ARCH: x86_64
      NVARCH: Linux_x86_64
      NVCOMPILERS: /opt/nvidia/hpc_sdk
      NVHPC_SILENT: true
      NVHPC_MAJOR: 22
      NVHPC_MINOR: 7
      CUDA_MAJOR: 11
      CUDA_MINOR: 7
      UBUNTU_VERSION: 2004
      LD_LIBRARY_PATH: /usr/local/lib
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -qq update

      - run: sudo apt-get -qq install libhdf5-dev
                                      liblapack-dev
                                      libopenmpi-dev

      # Install nvhpc
      # https://docs.nvidia.com/hpc-sdk/hpc-sdk-install-guide/index.html

      - run: |
        echo 'deb [trusted=yes] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' \
        | sudo tee /etc/apt/sources.list.d/nvhpc.list
        sudo apt-get -qq update
        sudo apt-get -qq install \
          --no-install-recommends nvhpc-${NVHPC_MAJOR}-${NVHPC_MINOR}

      - run: |
        source /etc/profile.d/modules.sh
        module load /opt/nvidia/hpc_sdk/modulefiles/nvhpc/${NVHPC_MAJOR}.${NVHPC_MINOR}

      - run: |
          which nvcc || echo "nvcc not in PATH!"
          which nvc++ || echo "nvc++ not in PATH!"
          which nvc || echo "nvc not in PATH!"
          which nvfortran || echo "nvfortran not in PATH!"
          nvcc --version
          nvc++ --version
          nvc --version
          nvfortran --version

      # Compile thornado

      - run: cd ${THORNADO_DIR}/SandBox/dgExperiments_Euler_Relativistic_IDEAL/Executables_nvhpc/
      - run: make HYDRO=RELATIVISTIC \
                  HYDRO_RIEMANN_SOLVER=HLL \
                  OPT_LEVEL=DEBUG \
                  USE_GPU=TRUE \
                  USE_OACC=TRUE \
                  USE_CUBLAS=TRUE
