name: Compile with nvhpc compiler

on:
  push:
    branches: [ InterfaceWithPoseidon ]
  pull_request:
    branches: [ InterfaceWithPoseidon ]

jobs:
  compile-with-nvhpc:
    name: Compile thornado with nvhpc on Ubuntu
    runs-on: ubuntu-latest
    env:
      THORNADO_MACHINE: gh-runner_nvhpc
      THORNADO_DIR: .
      NVARCH: Linux_x86_64
      NVCOMPILERS: /opt/nvidia/hpc_sdk
      NVHPC_SILENT: true
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -qq update
      - run: sudo apt-get -qq install libhdf5-dev liblapack-dev libopenmpi-dev
      - run: wget https://developer.download.nvidia.com/hpc-sdk/22.7/nvhpc_2022_227_Linux_x86_64_cuda_11.7.tar.gz
             1> /dev/null 2> /dev/null
      - run: tar xpzf nvhpc_2022_227_Linux_x86_64_cuda_11.7.tar.gz
             1> /dev/null 2> /dev/null
      - run: nvhpc_2022_227_Linux_x86_64_cuda_11.7/install
      - run: echo ${NVCOMPILERS}/${NVARCH}/22.7/compilers/bin >> ${GITHUB_PATH}
      - run: echo ${NVCOMPILERS}/${NVARCH}/22.7/comm_libs/mpi/bin >> ${GITHUB_PATH}
      - run: printenv | grep NV
      - run: echo ${PATH}
      - run: echo ${GITHUB_PATH}
      - run: |
          which nvcc || echo "nvcc not in PATH!"
          which nvc++ || echo "nvc++ not in PATH!"
          which nvc || echo "nvc not in PATH!"
          which nvfortran || echo "nvfortran not in PATH!"
          nvcc --version
          nvc++ --version
          nvc --version
          nvfortran --version

      - run: cd ${THORNADO_DIR}/SandBox/dgExperiments_Euler_Relativistic_IDEAL/Executables_nvhpc/
      - run: make HYDRO=RELATIVISTIC \
                  HYDRO_RIEMANN_SOLVER=HLL \
                  OPT_LEVEL=DEBUG \
                  FLAGS=-g,-O0,-Mbounds,-Mnoopenmp,-Ktrap=fp \
                  USE_GPU=TRUE \
                  USE_OACC=TRUE \
                  USE_CUBLAS=TRUE
