name: Compile with nvhpc compiler

on:
  push:
    branches: [ InterfaceWithPoseidon ]
  pull_request:
    branches: [ InterfaceWithPoseidon ]

jobs:
  compile-with-nvhpc:
    name: Compile thornado with nvhpc on Ubuntu
    runs-on: ubuntu-latest
    env:
      THORNADO_MACHINE: gh-runner_nvhpc
      THORNADO_DIR: .
      NVARCH: Linux_x86_64
      NVCOMPILERS: /opt/nvidia/hpc_sdk
      MANPATH: ${MANPATH}:${NVCOMPILERS}/${NVARCH}/22.7/compilers/man:${NVCOMPILERS}/${NVARCH}/22.7/comm_libs/mpi/man
      PATH: ${NVCOMPILERS}/${NVARCH}/22.7/compilers/bin:${NVCOMPILERS}/${NVARCH}/22.7/comm_libs/mpi/bin:${PATH}
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y libhdf5-dev liblapack-dev libopenmpi-dev
      - run: wget https://developer.download.nvidia.com/hpc-sdk/22.7/nvhpc_2022_227_Linux_x86_64_cuda_11.7.tar.gz
      - run: tar xpzf nvhpc_2022_227_Linux_x86_64_cuda_11.7.tar.gz
      - run: nvhpc_2022_227_Linux_x86_64_cuda_11.7/install
      - run: printenv | grep NV
      - run: echo ${PATH}
      - run: |
          which nvcc || echo "nvcc not in PATH!"
          which nvc++ || echo "nvc++ not in PATH!"
          which nvc || echo "nvc not in PATH!"
          which nvfortran || echo "nvfortran not in PATH!"
          nvcc --version
          nvc++ --version
          nvc --version
          nvfortran --version

      - run:
          cd ${THORNADO_DIR}/SandBox/dgExperiments_Euler_Relativistic_IDEAL/Executables_nvhpc/
          make HYDRO=RELATIVISTIC HYDRO_RIEMANN_SOLVER=HLL OPT_LEVEL=DEBUG FLAGS=$(FLAGS_DEBUG) USE_GPU=TRUE USE_OACC=TRUE USE_CUBLAS=TRUE
