name: Compile thornado on Ubuntu 20.04 with ROCm compilers

on: [ push, pull_request ]

jobs:
  compile-with-nvhpc:
    name: Compile thornado on Ubuntu 20.04 with ROCm compilers
    runs-on: ubuntu-20.04
    env:
      THORNADO_MACHINE: gh-runner_ubuntu-20.04_rocm
    steps:
      - name: Checkout thornado
        uses: actions/checkout@v3

      - name: Checkout weaklib
        uses: actions/checkout@v3
        with:
          repository: starkiller-astro/weaklib
          path: weaklib

      - name: Update Ubuntu
        run: |
          git branch
          sudo apt-get -qq update

      # https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.3/
      # page/Introduction_to_ROCm_Installation_Guide_for_Linux.html
      - name: Download and Install ROCm Suite
        run: |
          echo ""
          echo "uname -m && cat /etc/*release"
          uname -m && cat /etc/*release
          echo ""
          echo "uname -srmv"
          uname -srmv
          echo ""
          echo "sudo apt list --installed | grep 'wget\|gnupg2'"
          sudo apt list --installed | grep 'wget\|gnupg2'
          echo ""
          echo "sudo apt install linux-headers-`uname -r` linux-modules-extra-`uname -r`"
          sudo apt install linux-headers-`uname -r` linux-modules-extra-`uname -r`
          echo ""
          echo "sudo dpkg -l | grep linux-headers"
          sudo dpkg -l | grep linux-headers
          echo ""
          echo "sudo dpkg -l | grep linux-modules-extra"
          sudo dpkg -l | grep linux-modules-extra
          echo ""
          echo "wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -"
          wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
          echo 'deb [arch=amd64] https://repo.radeon.com/amdgpu/latest/ubuntu focal main' | sudo tee /etc/apt/sources.list.d/amdgpu.list
          echo ""
          echo "sudo apt-get update -qq"
          sudo apt-get update -qq
          echo ""
          echo "sudo apt install amdgpu-dkms"
          sudo apt install amdgpu-dkms
          echo ""
          echo "sudo apt install rocm-hip-runtime"
          sudo apt install rocm-hip-runtime
          echo ""
          echo "sudo apt install rocm-opencl-runtime"
          sudo apt install rocm-opencl-runtime
          echo ""
          echo "sudo apt install rocm-hip-runtime-devel"
          sudo apt install rocm-hip-runtime-devel
          echo ""
          echo "sudo apt install rocm-opencl-sdk"
          sudo apt install rocm-opencl-sdk
          echo ""
          echo "sudo apt install rocm-hip-libraries"
          sudo apt install rocm-hip-libraries
          echo ""
          echo "sudo apt install rocm-hip-sdk"
          sudo apt install rocm-hip-sdk
          echo ""
          echo "sudo apt install rocm-developer-tools"
          sudo apt install rocm-developer-tools

#      - name: Set Environment Variables
#        run: |
#          echo "THORNADO_DIR=${GITHUB_WORKSPACE}"        >> ${GITHUB_ENV}
#          echo "HDF5_DIR=${GITHUB_WORKSPACE}/hdf5"       >> ${GITHUB_ENV}
#          echo "HDF5_ROOT=${GITHUB_WORKSPACE}/hdf5"      >> ${GITHUB_ENV}
#          echo "WEAKLIB_DIR=${GITHUB_WORKSPACE}/weaklib" >> ${GITHUB_ENV}
#
#      - name: Check Environment and Find Libraries and Include Directories
#        run: |
#          echo ""
#          echo "ls ${THORNADO_DIR}"
#          ls ${THORNADO_DIR}
#          echo ""
#          echo "ls ${HDF5_DIR}"
#          ls ${HDF5_DIR}
#          echo ""
#          echo "ls ${WEAKLIB_DIR}"
#          ls ${WEAKLIB_DIR}
#
#      - name: Compile SandBox/dgExperiments_Euler_Relativistic_IDEAL/Executables
#        run: |
#          cd ${THORNADO_DIR}/SandBox/dgExperiments_Euler_Relativistic_IDEAL/Executables
#          make OPT_LEVEL=DEBUG \
#               HYDRO=RELATIVISTIC \
#               USE_GPU=TRUE \
#               USE_OACC=TRUE \
#               USE_CUBLAS=TRUE \
#               ApplicationDriver
#          make clobber
#
#      - name: Compile SandBox/dgExperiments_Euler_NonRelativistic_TABLE/Executables
#        run: |
#          cd ${THORNADO_DIR}/SandBox/dgExperiments_Euler_NonRelativistic_TABLE/Executables
#          make OPT_LEVEL=DEBUG \
#               USE_GPU=TRUE \
#               USE_OACC=TRUE \
#               USE_CUBLAS=TRUE \
#               ApplicationDriver
#          make clobber
#
#      - name: Compile SandBox/TwoMoment_OrderV/Executables
#        run: |
#          cd ${THORNADO_DIR}/SandBox/TwoMoment_OrderV/Executables
#          make OPT_LEVEL=DEBUG \
#               USE_GPU=TRUE \
#               USE_OACC=TRUE \
#               USE_CUBLAS=TRUE \
#               ApplicationDriver
#          make clobber
