name: Compile thornado on Ubuntu 20.04 with nvhpc compilers

on: [ push, pull_request ]

jobs:
  compile-with-nvhpc:
    name: Compile thornado on Ubuntu 20.04 with nvhpc compilers
    runs-on: ubuntu-20.04
    env:
      THORNADO_MACHINE: gh-runner_ubuntu-20.04_nvhpc
      ARCH: x86_64
      NVARCH: Linux_x86_64
      NVCOMPILERS: /opt/nvidia/hpc_sdk
      NVHPC_SILENT: true
      NVHPC_MAJOR: 23
      NVHPC_MINOR: 3
      CUDA_MAJOR: 12
      CUDA_MINOR: 0
      UBUNTU_VERSION: 2004
    steps:
      - name: Checkout thornado
        uses: actions/checkout@v3

      - name: Checkout weaklib
        uses: actions/checkout@v3
        with:
          repository: starkiller-astro/weaklib
          path: weaklib

      - name: Update Ubuntu
        run: |
          sudo apt-get -qqq update
          sudo apt-get install -y \
            environment-modules \
            libopenmpi-dev

      # https://developer.nvidia.com/hpc-sdk-downloads
      - name: Download and install nvhpc
        run: |
          find /usr -iname "*mpi.mod"
